swagger: "2.0"
info:
  description: Serverless Todo list
  version: 1.0.0
  title: Serverless Todo list

tags:
  - name: task
    description: タスクのエンティティ
  - name: user
    description: ユーザーのエンティティ

paths:
  /task:
    post:
      tags:
        - task
      summary: タスクの更新
      description: idを指定して、タスクの更新
      produces:
        - application/json
      parameters:
        - in: body
          name: TaskUpdateItem
          description: 更新したタスクのbody
          schema:
            $ref: "#/definitions/TaskUpdateItem"
      responses:
        201:
          description: タスクの更新完了
          schema:
            $ref: "#/definitions/TaskItem"
        404:
          description: 該当するタスクがない
  /task/{task_id}:
    get:
      tags:
        - task
      summary: 単一のタスクを取得する
      description: |
        idを指定して、単一のタスクを取得
      produces:
        - application/json
      parameters:
        - in: path
          name: task_id
          description: 取得したいタスクのID
          required: true
          type: string

      responses:
        200:
          description: 該当するタスクがある
          schema:
            $ref: "#/definitions/TaskItem"
        404:
          description: 該当するタスクがない
    post:
      tags:
        - task
      summary: タスクの更新
      description: idを指定して、タスクの更新
      produces:
        - application/json
      parameters:
        - in: path
          name: task_id
          description: 更新したいタスクのID
          required: true
          type: string
        - in: body
          name: TaskUpdateItem
          description: 更新したタスクのbody
          schema:
            $ref: "#/definitions/TaskUpdateItem"
      responses:
        201:
          description: タスクの更新完了
          schema:
            $ref: "#/definitions/TaskItem"
        404:
          description: 該当するタスクがない
    delete:
      tags:
        - task
      summary: タスクの削除
      description: idを指定して、タスクを削除する
      produces:
        - application/json
      parameters:
        - in: path
          name: task_id
          description: 更新したいタスクのID
          required: true
          type: string
      responses:
        200:
          description: タスクの削除完了
        404:
          description: 該当するタスクがない
  /tasks:
    get:
      tags:
        - task
      summary: タスクのリストを取得する
      operationId: searchInventory
      description: |
        idを指定して、単一のタスクを取得
      produces:
        - application/json
      responses:
        200:
          description: 該当するタスクがある
          schema:
            type: array
            items:
              $ref: "#/definitions/TaskItem"
        404:
          description: 該当するタスクがない
        400:
          description: パラメータが不正な場合
definitions:
  TaskItem:
    type: object
    required:
      - id
      - title
      - created_at
      - is_done
      - priority
    properties:
      id:
        type: string
        description: ulid
        example: "ABCDEFGHIJKLMNOPQRSTUVW000"
      title:
        type: string
        example: 宿題をする
        minLength: 1
        maxLength: 100
      content:
        type: string
        example: "テキストの100ページまでやる"
        minLength: 0
        maxLength: 2000
      is_done:
        type: boolean
        example: true
      priority:
        type: string
        enum:
          - high
          - medium
          - low
      created_at:
        type: number
        description: timestamp
        example: 1614260292.838746
      updated_at:
        type: number
        description: timestamp
        example: 1614260292.838746
  TaskUpdateItem:
    type: object
    required:
      - title
      - is_done
      - priority
    properties:
      title:
        type: string
        minLength: 1
        maxLength: 100
      content:
        type: string
        minLength: 1
        maxLength: 2000
      is_done:
        type: boolean
        example: true
      priority:
        type: string
        enum:
          - high
          - medium
          - low
